name: kings gatehouse
favicon: null
layout_spectrum: 0.8430905246641487
typography_spectrum: 0.9073170411866158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9024389192927629
  lightness: 0.15812261123210192
  saturation: 0.9999289843253791
  rhythmicContrast: 0.6679169365670532
purpose: []
